### ISSUE TITLE
Token list not updating in web app

### ISSUE THREAD

**Issue by simonmcl** [tachyswap/tokenlist#5]
The token list doesn't seem to be updating in the web app. It appears as though its being cached for a very long time and not fetching the updated list. My main browser (brave) has been stuck on this list for several weeks, but if I open in a new browser it displays the more recent tokens added

![Screenshot 2024-07-17 at 15 17 36](https://github.com/user-attachments/assets/83a05ee7-4ea0-4f00-a96b-5a6e9a3017c8)

**Comment by tachyswap** [comment]
should be fixed for everyone now
